/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airportmang;
import java.sql.*;
import java.awt.event.MouseWheelEvent;
import java.awt.event.MouseWheelListener;
import java.io.IOException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dweep
 */
public class check_in extends javax.swing.JFrame {
   static ResultSet rs;
   DefaultTableModel flightTable;
   Integer boarded_count,not_boarded_count;
   Connection con;
   
    /**
     * Creates new form check_in
     */
    public check_in() throws SQLException, ClassNotFoundException {
//        this.setSize(800,800);
//        this.setVisible(true);
        
        Class.forName("com.mysql.jdbc.Driver");
        
        con = DriverManager.getConnection("jdbc:mysql://localhost:3306/airport", "root", "");
        
        Statement st = con.createStatement();
        Statement st2 = con.createStatement();
        
         rs = st.executeQuery("select * from passenger_info");
         ResultSet flightInfo = st2.executeQuery("select * from flight_info");
         
         flightTable = buildTableModel(flightInfo);
         
        initComponents();
        
        boarded_count = 0;
        not_boarded_count = jTable1.getRowCount();
        
        boarded_count_label.setText(boarded_count.toString());
        not_boarded_count_label.setText(not_boarded_count.toString());
        
        con.close();        
    }
    
    public static DefaultTableModel buildTableModel(ResultSet rs)
        throws SQLException {

    ResultSetMetaData metaData = rs.getMetaData();

    // names of columns
    Vector<String> columnNames = new Vector<String>();
    int columnCount = metaData.getColumnCount();
    for (int column = 1; column <= columnCount; column++) {
        columnNames.add(metaData.getColumnName(column));
    }

    // data of the table
    Vector<Vector<Object>> data = new Vector<Vector<Object>>();
    while (rs.next()) {
        Vector<Object> vector = new Vector<Object>();
        for (int columnIndex = 1; columnIndex <= columnCount; columnIndex++) {
            vector.add(rs.getObject(columnIndex));
        }
        data.add(vector);
    }

    return new DefaultTableModel(data, columnNames);

}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        boarding_status_panel = new javax.swing.JPanel();
        boarded_label = new javax.swing.JLabel();
        not_boarded_label = new javax.swing.JLabel();
        boarded_count_label = new javax.swing.JLabel();
        not_boarded_count_label = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        try{
            jTable1 = new javax.swing.JTable(buildTableModel(rs));
            boarding_status_panel1 = new javax.swing.JPanel();
            boarded_label1 = new javax.swing.JLabel();
            not_boarded_label1 = new javax.swing.JLabel();
            ref_id_txtfld = new javax.swing.JTextField();
            flight_no_txtfld = new javax.swing.JTextField();
            board_button = new javax.swing.JButton();
            cancel_button = new javax.swing.JButton();
            jPanel1 = new javax.swing.JPanel();
            flightno_label = new javax.swing.JLabel();
            flightNo_info_label = new javax.swing.JLabel();
            flightName_label = new javax.swing.JLabel();
            flightName_info_label = new javax.swing.JLabel();
            arrivalTime_label = new javax.swing.JLabel();
            arrivalTime_info_label = new javax.swing.JLabel();
            departureTime_label = new javax.swing.JLabel();
            departureTime_info_label = new javax.swing.JLabel();
            source_label = new javax.swing.JLabel();
            destination_label = new javax.swing.JLabel();
            source_info_label = new javax.swing.JLabel();
            destination_info_label = new javax.swing.JLabel();
            date_label = new javax.swing.JLabel();
            gate_label = new javax.swing.JLabel();
            date_info_label = new javax.swing.JLabel();
            gate_info_label = new javax.swing.JLabel();
            logout_button = new javax.swing.JButton();
            users_name = new javax.swing.JLabel();

            javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
            jFrame1.getContentPane().setLayout(jFrame1Layout);
            jFrame1Layout.setHorizontalGroup(
                jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 400, Short.MAX_VALUE)
            );
            jFrame1Layout.setVerticalGroup(
                jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 300, Short.MAX_VALUE)
            );

            javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
            jFrame2.getContentPane().setLayout(jFrame2Layout);
            jFrame2Layout.setHorizontalGroup(
                jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 400, Short.MAX_VALUE)
            );
            jFrame2Layout.setVerticalGroup(
                jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 300, Short.MAX_VALUE)
            );

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

            boarding_status_panel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Boarding Status"));
            boarding_status_panel.setName("Boarding Status"); // NOI18N

            boarded_label.setText("Boarded:");

            not_boarded_label.setText("Not Boarded:");

            boarded_count_label.setText("jLabel3");

            not_boarded_count_label.setText("jLabel4");

            javax.swing.GroupLayout boarding_status_panelLayout = new javax.swing.GroupLayout(boarding_status_panel);
            boarding_status_panel.setLayout(boarding_status_panelLayout);
            boarding_status_panelLayout.setHorizontalGroup(
                boarding_status_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(boarding_status_panelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(boarding_status_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(boarding_status_panelLayout.createSequentialGroup()
                            .addComponent(not_boarded_label)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 256, Short.MAX_VALUE)
                            .addComponent(not_boarded_count_label, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(boarding_status_panelLayout.createSequentialGroup()
                            .addComponent(boarded_label)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(boarded_count_label, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(22, 22, 22))
            );
            boarding_status_panelLayout.setVerticalGroup(
                boarding_status_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(boarding_status_panelLayout.createSequentialGroup()
                    .addGap(41, 41, 41)
                    .addGroup(boarding_status_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(boarded_label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(boarded_count_label, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(boarding_status_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(not_boarded_label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(not_boarded_count_label, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(jTable1);

        boarding_status_panel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "CHECK-IN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 0, 10), java.awt.Color.black)); // NOI18N
        boarding_status_panel1.setName("Boarding Status"); // NOI18N

        boarded_label1.setText("Ref. ID:");

        not_boarded_label1.setText("Flight No.:");

        board_button.setText("Board");
        board_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                board_buttonActionPerformed(evt);
            }
        });

        cancel_button.setText("Cancel");
        cancel_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout boarding_status_panel1Layout = new javax.swing.GroupLayout(boarding_status_panel1);
        boarding_status_panel1.setLayout(boarding_status_panel1Layout);
        boarding_status_panel1Layout.setHorizontalGroup(
            boarding_status_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boarding_status_panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(boarding_status_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boarded_label1)
                    .addComponent(not_boarded_label1))
                .addGap(27, 27, 27)
                .addGroup(boarding_status_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ref_id_txtfld)
                    .addComponent(flight_no_txtfld, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(boarding_status_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(board_button, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                    .addComponent(cancel_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        boarding_status_panel1Layout.setVerticalGroup(
            boarding_status_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boarding_status_panel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(boarding_status_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boarded_label1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ref_id_txtfld, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(board_button, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE))
                .addGroup(boarding_status_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(boarding_status_panel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(boarding_status_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(not_boarded_label1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(flight_no_txtfld, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(boarding_status_panel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(cancel_button, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "FLIGHT-INFORMATION"));

        flightno_label.setText("Flight Number:");

        flightName_label.setText("Name:");

        arrivalTime_label.setText("Arrival Time:");

        departureTime_label.setText("Departure Time:");

        source_label.setText("Source:");

        destination_label.setText("Destination:");

        date_label.setText("Date:");

        gate_label.setText("Gate:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(flightno_label)
                    .addComponent(flightName_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(flightNo_info_label, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(flightName_info_label, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(arrivalTime_info_label, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(arrivalTime_label)
                            .addComponent(departureTime_label))
                        .addGap(18, 18, 18)
                        .addComponent(departureTime_info_label)))
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(destination_label)
                    .addComponent(source_label))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(source_info_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(destination_info_label, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE))
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(date_label)
                    .addComponent(gate_label))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(date_info_label)
                    .addComponent(gate_info_label))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(flightno_label, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(flightNo_info_label, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(arrivalTime_label)
                    .addComponent(arrivalTime_info_label)
                    .addComponent(source_label)
                    .addComponent(source_info_label)
                    .addComponent(date_label)
                    .addComponent(date_info_label))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(flightName_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(flightName_info_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(departureTime_label)
                    .addComponent(departureTime_info_label)
                    .addComponent(destination_label)
                    .addComponent(destination_info_label)
                    .addComponent(gate_label)
                    .addComponent(gate_info_label))
                .addGap(46, 46, 46))
        );

        logout_button.setText("Logout");
        logout_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addGap(69, 69, 69))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(users_name, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logout_button))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(boarding_status_panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(boarding_status_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logout_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(users_name, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(boarding_status_panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boarding_status_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void board_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_board_buttonActionPerformed
        int i=0;
        while(!ref_id_txtfld.getText().equals("") && !flight_no_txtfld.getText().equals("") && i<jTable1.getRowCount())
        {
            if(ref_id_txtfld.getText().equals(jTable1.getValueAt(i, 0).toString()))
            {
                JOptionPane.showMessageDialog(this,"Boarded");
                boarded_count++;
                not_boarded_count--;
                boarded_count_label.setText(boarded_count.toString());
                not_boarded_count_label.setText(not_boarded_count.toString());
                int j=0;
               
                while(j<flightTable.getRowCount())
                {
                    if(flightTable.getValueAt(j, 0).toString().equals(flight_no_txtfld.getText()))
                    {
                        flightNo_info_label.setText(flightTable.getValueAt(j, 0).toString());
                        flightName_info_label.setText(flightTable.getValueAt(j, 1).toString());
                        date_info_label.setText(flightTable.getValueAt(j, 2).toString());
                        arrivalTime_info_label.setText(flightTable.getValueAt(j, 3).toString());
                        departureTime_info_label.setText(flightTable.getValueAt(j, 4).toString());
                        source_info_label.setText(flightTable.getValueAt(j, 5).toString());
                        destination_info_label.setText(flightTable.getValueAt(j, 6).toString());
                        gate_info_label.setText(flightTable.getValueAt(j, 8).toString());
                    }
                   j++;
                }
                
                break;
            }
            i++;
        }
        if(i == jTable1.getRowCount())  
            JOptionPane.showMessageDialog(this,"Record Not Found!");
        
//       try {
//         con.close();
//       } catch (SQLException ex) {
//           Logger.getLogger(check_in.class.getName()).log(Level.SEVERE, null, ex);
//       }
    }//GEN-LAST:event_board_buttonActionPerformed

    private void logout_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_buttonActionPerformed
       log_in logout=null;
       try {
           logout = new log_in();
       } catch (IOException ex) {
           Logger.getLogger(check_in.class.getName()).log(Level.SEVERE, null, ex);
       }
       logout.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_logout_buttonActionPerformed

    private void cancel_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_buttonActionPerformed
      ref_id_txtfld.setText("");
      flight_no_txtfld.setText("");
    }//GEN-LAST:event_cancel_buttonActionPerformed

    /*
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ClassNotFoundException, SQLException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(check_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(check_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(check_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(check_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new check_in().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(check_in.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(check_in.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
            
        });
        
       
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel arrivalTime_info_label;
    private javax.swing.JLabel arrivalTime_label;
    private javax.swing.JButton board_button;
    private javax.swing.JLabel boarded_count_label;
    private javax.swing.JLabel boarded_label;
    private javax.swing.JLabel boarded_label1;
    private javax.swing.JPanel boarding_status_panel;
    private javax.swing.JPanel boarding_status_panel1;
    private javax.swing.JButton cancel_button;
    private javax.swing.JLabel date_info_label;
    private javax.swing.JLabel date_label;
    private javax.swing.JLabel departureTime_info_label;
    private javax.swing.JLabel departureTime_label;
    private javax.swing.JLabel destination_info_label;
    private javax.swing.JLabel destination_label;
    private javax.swing.JLabel flightName_info_label;
    private javax.swing.JLabel flightName_label;
    private javax.swing.JLabel flightNo_info_label;
    private javax.swing.JTextField flight_no_txtfld;
    private javax.swing.JLabel flightno_label;
    private javax.swing.JLabel gate_info_label;
    private javax.swing.JLabel gate_label;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton logout_button;
    private javax.swing.JLabel not_boarded_count_label;
    private javax.swing.JLabel not_boarded_label;
    private javax.swing.JLabel not_boarded_label1;
    private javax.swing.JTextField ref_id_txtfld;
    private javax.swing.JLabel source_info_label;
    private javax.swing.JLabel source_label;
    public javax.swing.JLabel users_name;
    // End of variables declaration//GEN-END:variables

}
