/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airportmang;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Dweep
 */
public class registrationForm extends javax.swing.JFrame {

    /**
     * Creates new form registrationForm
     */
    public registrationForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        id_label = new javax.swing.JLabel();
        password_label = new javax.swing.JLabel();
        name_label = new javax.swing.JLabel();
        job_label = new javax.swing.JLabel();
        contact_label = new javax.swing.JLabel();
        id_textField = new javax.swing.JTextField();
        password_textField = new javax.swing.JTextField();
        name_textField = new javax.swing.JTextField();
        contact_textField = new javax.swing.JTextField();
        heading_label = new javax.swing.JLabel();
        submit_button = new javax.swing.JButton();
        cancel_button = new javax.swing.JButton();
        job_combobox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        id_label.setText("Id:");

        password_label.setText("Password:");

        name_label.setText("Name:");

        job_label.setText("Job:");

        contact_label.setText("Contact:");

        id_textField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_textFieldActionPerformed(evt);
            }
        });

        password_textField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password_textFieldActionPerformed(evt);
            }
        });

        name_textField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_textFieldActionPerformed(evt);
            }
        });

        heading_label.setText("Registration Form:");

        submit_button.setText("Submit");
        submit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_buttonActionPerformed(evt);
            }
        });

        cancel_button.setText("Cancel");
        cancel_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_buttonActionPerformed(evt);
            }
        });

        job_combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select...", "employee", "admin" }));
        job_combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                job_comboboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(heading_label)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(password_label)
                            .addComponent(contact_label)
                            .addComponent(job_label)
                            .addComponent(name_label)
                            .addComponent(id_label))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(submit_button)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cancel_button)
                                .addGap(48, 48, 48))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(id_textField)
                                    .addComponent(password_textField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(name_textField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(contact_textField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(job_combobox, 0, 130, Short.MAX_VALUE))
                                .addGap(436, 436, 436))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(heading_label)
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id_label)
                    .addComponent(id_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password_label)
                    .addComponent(password_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name_label)
                    .addComponent(name_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(job_label)
                    .addComponent(job_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contact_label)
                    .addComponent(contact_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submit_button)
                    .addComponent(cancel_button))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void password_textFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password_textFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_password_textFieldActionPerformed

    private void name_textFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_textFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_textFieldActionPerformed

    private void submit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_buttonActionPerformed
        if(!id_textField.getText().equals("") && !password_textField.getText().equals("") && !name_textField.getText().equals("") && !job_combobox.getSelectedItem().toString().equals("select...") && !contact_textField.getText().equals("") )
        {
            try {
                try {
                    Class.forName("com.mysql.jdbc.Driver");
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(registrationForm.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                Connection con = null;
                try {
                    con = DriverManager.getConnection("jdbc:mysql://localhost/airport", "root", "");
                } catch (SQLException ex) {
                    Logger.getLogger(registrationForm.class.getName()).log(Level.SEVERE, null, ex);
                }
               
                Statement st = con.createStatement();  
                st.executeUpdate("insert into employee_info values('"+id_textField.getText()+"','"+password_textField.getText()+"','"+name_textField.getText()+"','"+job_combobox.getSelectedItem().toString()+"',"+contact_textField.getText()+")");
                con.close();
            } catch (SQLException ex) {
                Logger.getLogger(registrationForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(this, "Done!");
            admin_page cancel;
            try {
                cancel = new admin_page();
                cancel.setVisible(true);
                this.setVisible(false);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(registrationForm.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(registrationForm.class.getName()).log(Level.SEVERE, null, ex);
            }
           
        }
        else if(id_textField.getText().equals(""))
            JOptionPane.showMessageDialog(this, "Id required!");
        else if(password_textField.getText().equals(""))
            JOptionPane.showMessageDialog(this, "Password required!");
        else if(name_textField.getText().equals(""))
            JOptionPane.showMessageDialog(this, "Name required!");
        else if(job_combobox.getSelectedItem().toString().equals("select..."))
            JOptionPane.showMessageDialog(this, "Job description required!");
        else if(contact_textField.getText().equals(""))
            JOptionPane.showMessageDialog(this, "Contact required!");
        
    }//GEN-LAST:event_submit_buttonActionPerformed

    private void id_textFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_textFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_textFieldActionPerformed

    private void cancel_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_buttonActionPerformed
        // TODO add your handling code here:
        admin_page cancel;
        try {
            cancel = new admin_page();
            cancel.setVisible(true);
            this.setVisible(false);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(registrationForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(registrationForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_cancel_buttonActionPerformed

    private void job_comboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_job_comboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_job_comboboxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registrationForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel_button;
    private javax.swing.JLabel contact_label;
    private javax.swing.JTextField contact_textField;
    private javax.swing.JLabel heading_label;
    private javax.swing.JLabel id_label;
    private javax.swing.JTextField id_textField;
    private javax.swing.JComboBox<String> job_combobox;
    private javax.swing.JLabel job_label;
    private javax.swing.JLabel name_label;
    private javax.swing.JTextField name_textField;
    private javax.swing.JLabel password_label;
    private javax.swing.JTextField password_textField;
    private javax.swing.JButton submit_button;
    // End of variables declaration//GEN-END:variables
}
